name: Deploy Lambda

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write   # required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (if you build a Python Lambda)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # If your Lambda needs dependencies, install them into a folder to zip
      # - run: |
      #     python -m pip install -r lambda/requirements.txt -t lambda/

      - name: Create deployment package
        run: |
          mkdir -p build
          # Example: zip everything in lambda/ (change to your path)
          cd lambda
          zip -r ../build/function.zip .
          cd ..

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<ROLE_NAME_FOR_GITHUB>
          aws-region: <REGION>

      - name: Upload to S3 (optional if you update Lambda direct from zip)
        if: ${{ env.S3_BUCKET != '' }}
        env:
          S3_BUCKET: "" # set to your bucket or leave empty to skip
        run: |
          if [ -n "$S3_BUCKET" ]; then
            aws s3 cp build/function.zip s3://$S3_BUCKET/lambda/function.zip
          fi

      - name: Update Lambda code (direct upload)
        run: |
          aws lambda update-function-code \
            --function-name resume-template \
            --zip-file fileb://build/function.zip \
            --publish
